var typeList = [
  {
    id: 1,
    name: "娱乐",
    icon: [
      "iconFun/yule_1.png",
      "iconFun/yule_2.png",
      "iconFun/yule_3.png",
      "iconFun/yule_4.png",
      "iconFun/yule_5.png",
      "iconFun/yule_6.png",
      "iconFun/yule_7.png",
      "iconFun/yule_8.png",
      "iconFun/yule_9.png",
      "iconFun/yule_10.png",
      "iconFun/yule_11.png",
      "iconFun/yule_12.png",
      "iconFun/yule_13.png",
      "iconFun/yule_14.png",
      "iconFun/yule_15.png",
      "iconFun/yule_16.png",
      "iconFun/yule_17.png",
    ],
  },
  {
    id: 2,
    name: "饮食",
    icon: [
      "iconFood/food_1.png",
      "iconFood/food_2.png",
      "iconFood/food_3.png",
      "iconFood/food_4.png",
      "iconFood/food_5.png",
      "iconFood/food_6.png",
      "iconFood/food_7.png",
      "iconFood/food_8.png",
      "iconFood/food_9.png",
      "iconFood/food_10.png",
      "iconFood/food_11.png",
      "iconFood/food_12.png",
      "iconFood/food_13.png",
      "iconFood/food_14.png",
      "iconFood/food_15.png",
      "iconFood/food_16.png",
      "iconFood/food_17.png",
      "iconFood/food_18.png",
    ],
  },
  {
    id: 3,
    name: "交通",
    icon: [
      "iconCar/car_1.png",
      "iconCar/car_2.png",
      "iconCar/car_3.png",
      "iconCar/car_4.png",
      "iconCar/car_5.png",
      "iconCar/car_6.png",
      "iconCar/car_7.png",
    ],
  },
  {
    id: 4,
    name: "生活",
    icon: [
      "iconLife/life_1.png",
      "iconLife/life_2.png",
      "iconLife/life_3.png",
      "iconLife/life_4.png",
      "iconLife/life_5.png",
      "iconLife/life_6.png",
      "iconLife/life_7.png",
      "iconLife/life_8.png",
      "iconLife/life_9.png",
      "iconLife/life_10.png",
      "iconLife/life_11.png",
      "iconLife/life_12.png",
      "iconLife/life_13.png",
      "iconLife/life_14.png",
    ],
  },
  {
    id: 5,
    name: "医疗",
    icon: [
      "iconHospital/hospital_1.png",
      "iconHospital/hospital_2.png",
      "iconHospital/hospital_3.png",
      "iconHospital/hospital_4.png",
      "iconHospital/hospital_5.png",
      "iconHospital/hospital_6.png",
      "iconHospital/hospital_7.png",
      "iconHospital/hospital_8.png",
      "iconHospital/hospital_9.png",
    ],
  },
  {
    id: 6,
    name: "学习",
    icon: [
      "iconStudy/study_1.png",
      "iconStudy/study_2.png",
      "iconStudy/study_3.png",
      "iconStudy/study_4.png",
      "iconStudy/study_5.png",
      "iconStudy/study_6.png",
      "iconStudy/study_7.png",
    ],
  },
  {
    id: 7,
    name: "办公",
    icon: [
      "iconWork/work_1.png",
      "iconWork/work_2.png",
      "iconWork/work_3.png",
      "iconWork/work_4.png",
      "iconWork/work_5.png",
      "iconWork/work_6.png",
      "iconWork/work_7.png",
      "iconWork/work_8.png",
    ],
  },
  {
    id: 8,
    name: "家居",
    icon: [
      "iconHome/home_1.png",
      "iconHome/home_2.png",
      "iconHome/home_3.png",
      "iconHome/home_4.png",
      "iconHome/home_5.png",
      "iconHome/home_6.png",
      "iconHome/home_7.png",
      "iconHome/home_8.png",
      "iconHome/home_9.png",
      "iconHome/home_10.png",
      "iconHome/home_11.png",
      "iconHome/home_12.png",
      "iconHome/home_13.png",
      "iconHome/home_14.png",
      "iconHome/home_15.png",
    ],
  },
  {
    id: 9,
    name: "收入",
    icon: [
      "iconIncome/income_1.png",
      "iconIncome/income_2.png",
      "iconIncome/income_3.png",
      "iconIncome/income_4.png",
      "iconIncome/income_5.png",
      "iconIncome/income_6.png",
      "iconIncome/income_7.png",
      "iconIncome/income_8.png",
    ],
  },
];
export default typeList;
